=== IngSolutionPA/S-Sign/afirma-simple-plugins/src/test/resources/schema.json
{

  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "info": {
      "type": "object",
      "properties": {
        "name":		 			{ "type": "string" },
        "title":				{ "type": "string" },
        "version_code":			{ "type": "integer", "default": 1 },
        "version":				{ "type": "string", "default": "1.0" },
        "authors":				{
        							"type": "array",
          							"items": { "type": "string" },
          							"default": []
          						},
        "contacts":				{
        							"type": "array",
          							"items": { "type": "string" },
          							"default": []
          						},
        "description":			{ "type": "string" },
        "configuration_panel":	{ "type": "string" }
      },
      "required": ["name", "title", "description"]
    },
    
    "permissions": {
	   	"type":		"array",
		"items":	{
						"type": "string",
						"enum": [
							"INSTALL",
							"UNINSTALL",
							"RESET",
							"INLINE_PROCESS",
							"PRESIGN",
							"POSTSIGN",
							"BUTTONS",
							"MENU",
							"COMMANDS" ]
					},
		"default":	[]
    },

    "button": {
      "type": "object",
      "properties": {
        "title":				{ "type": "string" },
        "icon":					{ "type": "string" },
        "tooltip":				{ "type": "string" },
        "accesible_description":{ "type": "string" },
        "window":				{ "type": "string", "enum": [ "input", "single_result", "multi_result", "visor" ] },
        "action":				{ "type": "string" }
      },
      "required": ["window", "action"]
    },

    "menu": {
      "type": "object",
      "properties": {
        "title": 	{ "type": "string" },
        "action":	{ "type": "string" },
	    "items":	{ 
				    	"type": "array",
				        "items": { "$ref": "#/definitions/menu" },
				        "default": []
				    }
      },
      "required": ["title"]
    },
    
    "command": {
      "type": "object",
      "properties": {
        "name":					{ "type": "string" },
        "description":			{ "type": "string" },
        "action":				{ "type": "string" }
      },
      "required": ["name", "action"]
    }
  },

  "type": "object",

  "properties": {
    "info": 			{ "$ref": "#/definitions/info" },
    "permissions":		{ "$ref": "#/definitions/permissions" },
    "inline_processor":	{ "type": "string" },
    "menu":				{ "$ref": "#/definitions/menu" },
    "buttons":			{ 
				    		"type": "array",
					        "items": { "$ref": "#/definitions/button" },
					        "default": []
					    },
    "commands":			{ 
					    	"type": "array",
					        "items": { "$ref": "#/definitions/command" },
					        "default": []
					    }
  },
  
  "required": ["info"]
}

=== IngSolutionPA/S-Sign/afirma-simple-plugin-hash/src/main/resources/es/gob/afirma/plugin/hash/plugin.json
{
	"info": {
		"name": "hash",
		"title": "Huellas digitales",
		"version_code": 1,
		"version": "1.0",
		"authors": [
			"Gobierno de España"
		],
		"description": "Plugin para el cálculo y la comprobación de hashes.<br><br>El componente permite generar ficheros de hashes con el hash de un fichero o de todos los ficheros de un directorio. También permite comprobar que un fichero de hashes es válido seleccionando el fichero o directorio a partir del cuál se generó.<br><br>El plugin permite realizar las nuevas operaciones tanto desde interfaces gráficos como desde línea de comandos."
	},
	"permissions": ["INSTALL","RESET", "MENU", "COMMANDS"],
	"menu": {
		"title": "Huellas digitales",
		"items": [
			{
				"title": "Fichero",
				"items": [
					{
						"title": "Calcular huella digital",
						"action": "es.gob.afirma.plugin.hash.action.CalculateHashFileAction"
					},
					{
						"title": "Comprobar huella digital",
						"action": "es.gob.afirma.plugin.hash.action.CheckHashFileAction"
					}
				]
			},
			{
				"title": "Directorio",
				"items": [
					{
						"title": "Calcular huella digital en directorio",
						"action": "es.gob.afirma.plugin.hash.action.CalculateHashDirAction"
					},
					{
						"title": "Comprobar huella digital en directorio",
						"action": "es.gob.afirma.plugin.hash.action.CheckHashDirAction"
					}
				]
			}
		]
	},
	"commands": [
		{
			"name": "createdigest",
			"description": "Creaci�n de huellas digitales con interfaz gr�fica",
			"action": "es.gob.afirma.plugin.hash.command.CreateHashCommand"
		},
		{
			"name": "checkdigest",
			"description": "Comprobaci�n de huellas digitales con interfaz gr�fica",
			"action": "es.gob.afirma.plugin.hash.command.CheckHashCommand"
		}
	]
}
